from .db import mongo


def seed_products_if_empty() -> None:
    """
    Seed initial products and medicines into MongoDB if collections are empty.
    Prices are treated as INR amounts; the frontend already formats them as INR.
    """
    if mongo.db.products.count_documents({}) == 0:
        products = [
            {
                "name": "Premium Dog Leash",
                "category": "Accessories",
                "petType": "Dog",
                "price": 599.99,
                "imageUrl": "/mock/leash.png",
                "rating": 4.6,
                "stock": 42,
                "description": "Soft grip, durable nylon leash perfect for daily walks.",
            },
            {
                "name": "Cat Scratching Post",
                "category": "Accessories",
                "petType": "Cat",
                "price": 399.99,
                "imageUrl": "/mock/scratching.png",
                "rating": 4.4,
                "stock": 18,
                "description": "Stable scratching post with comfy perch to keep claws healthy.",
            },
            {
                "name": "Healthy Treats Pack",
                "category": "Food",
                "petType": "Dog",
                "price": 1299.5,
                "imageUrl": "/mock/treats.png",
                "rating": 4.8,
                "stock": 70,
                "description": "High-protein treats with no artificial colors.",
            },
            # Additional pet care products (commonly found online)
            {
                "name": "Stainless Steel Dog Bowl Set",
                "category": "Accessories",
                "petType": "Dog",
                "price": 449.00,
                "imageUrl": "/mock/bowl.png",
                "rating": 4.7,
                "stock": 55,
                "description": "Durable, non-slip double bowl set. Easy to clean, dishwasher safe.",
            },
            {
                "name": "Orthopedic Dog Bed",
                "category": "Accessories",
                "petType": "Dog",
                "price": 2499.00,
                "imageUrl": "/mock/bed.png",
                "rating": 4.5,
                "stock": 28,
                "description": "Memory foam bed for joint support. Removable, machine-washable cover.",
            },
            {
                "name": "Adjustable Dog Collar with ID Tag",
                "category": "Accessories",
                "petType": "Dog",
                "price": 349.00,
                "imageUrl": "/mock/collar.png",
                "rating": 4.6,
                "stock": 90,
                "description": "Nylon collar with reflective strip. Includes engraved ID tag slot.",
            },
            {
                "name": "Pet Grooming Kit (Brush, Nail Clipper, Comb)",
                "category": "Grooming",
                "petType": "Dog",
                "price": 799.00,
                "imageUrl": "/mock/grooming.png",
                "rating": 4.4,
                "stock": 35,
                "description": "Complete grooming set for coat and nail care. Suitable for small to medium dogs.",
            },
            {
                "name": "Dental Chew Sticks for Dogs",
                "category": "Food",
                "petType": "Dog",
                "price": 499.00,
                "imageUrl": "/mock/dental.png",
                "rating": 4.7,
                "stock": 120,
                "description": "Natural dental chews that reduce tartar and freshen breath. Vet recommended.",
            },
            {
                "name": "Cat Litter Box with Hood",
                "category": "Accessories",
                "petType": "Cat",
                "price": 1299.00,
                "imageUrl": "/mock/litter.png",
                "rating": 4.5,
                "stock": 22,
                "description": "Enclosed litter box with carbon filter to control odor. Easy to clean.",
            },
            {
                "name": "Interactive Cat Toy Set",
                "category": "Toys",
                "petType": "Cat",
                "price": 599.00,
                "imageUrl": "/mock/cattoys.png",
                "rating": 4.6,
                "stock": 45,
                "description": "Feather wand, ball track, and mouse toys. Keeps cats active and engaged.",
            },
            {
                "name": "Premium Dry Cat Food (1.5 kg)",
                "category": "Food",
                "petType": "Cat",
                "price": 899.00,
                "imageUrl": "/mock/catfood.png",
                "rating": 4.8,
                "stock": 80,
                "description": "Complete nutrition with real chicken. No artificial preservatives or colors.",
            },
            {
                "name": "Fish Aquarium Filter Pump",
                "category": "Accessories",
                "petType": "Fish",
                "price": 699.00,
                "imageUrl": "/mock/filter.png",
                "rating": 4.3,
                "stock": 30,
                "description": "Submersible filter pump for tanks up to 40L. Quiet operation.",
            },
            {
                "name": "Small Animal Exercise Wheel",
                "category": "Toys",
                "petType": "Small Pet",
                "price": 449.00,
                "imageUrl": "/mock/wheel.png",
                "rating": 4.5,
                "stock": 25,
                "description": "Silent spinner wheel for hamsters and gerbils. Easy to attach to cage.",
            },
        ]
        mongo.db.products.insert_many(products)

    medicines = [
        {
            "name": "Deworming Tablets",
            "category": "Medicine",
            "petType": "Dog",
            "price": 89.99,
            "imageUrl": "/mock/medicine.png",
            "rating": 4.3,
            "stock": 120,
            "description": "Monthly deworming support. Consult your vet for dosage.",
            "prescriptionRequired": True,
        },
        {
            "name": "Flea & Tick Spray",
            "category": "Medicine",
            "petType": "Cat",
            "price": 149.99,
            "imageUrl": "/mock/medicine2.png",
            "rating": 4.5,
            "stock": 65,
            "description": "Helps reduce fleas & ticks. For external use only.",
            "prescriptionRequired": False,
        },
        {
            "name": "Joint Care Supplement for Dogs",
            "category": "Supplement",
            "petType": "Dog",
            "price": 599.00,
            "imageUrl": "/mock/joint.png",
            "rating": 4.6,
            "stock": 75,
            "description": "Glucosamine and chondroitin for joint health. Supports mobility in senior dogs.",
            "prescriptionRequired": False,
        },
        {
            "name": "Multivitamin Drops for Cats",
            "category": "Supplement",
            "petType": "Cat",
            "price": 349.00,
            "imageUrl": "/mock/vitamin.png",
            "rating": 4.4,
            "stock": 90,
            "description": "Liquid multivitamin with taurine. Supports immunity and coat health.",
            "prescriptionRequired": False,
        },
        {
            "name": "Ear Cleaner Solution for Dogs & Cats",
            "category": "Medicine",
            "petType": "Dog",
            "price": 249.00,
            "imageUrl": "/mock/ear.png",
            "rating": 4.7,
            "stock": 60,
            "description": "Gentle ear cleaning solution. Helps prevent ear infections. Use as directed.",
            "prescriptionRequired": False,
        },
        {
            "name": "Calming Tablets for Anxious Pets",
            "category": "Medicine",
            "petType": "Dog",
            "price": 429.00,
            "imageUrl": "/mock/calm.png",
            "rating": 4.3,
            "stock": 50,
            "description": "Natural calming aid for travel and separation anxiety. Non-drowsy formula.",
            "prescriptionRequired": False,
        },
        {
            "name": "Antibacterial Skin Ointment",
            "category": "Medicine",
            "petType": "Dog",
            "price": 199.00,
            "imageUrl": "/mock/ointment.png",
            "rating": 4.5,
            "stock": 85,
            "description": "For minor cuts, scrapes, and hot spots. Consult vet for deep wounds.",
            "prescriptionRequired": False,
        },
        {
            "name": "Deworming Syrup for Puppies",
            "category": "Medicine",
            "petType": "Dog",
            "price": 129.00,
            "imageUrl": "/mock/deworm.png",
            "rating": 4.6,
            "stock": 100,
            "description": "Broad-spectrum dewormer for puppies. Follow vet-recommended schedule.",
            "prescriptionRequired": True,
        },
        {
            "name": "Flea & Tick Spot-On for Cats",
            "category": "Medicine",
            "petType": "Cat",
            "price": 399.00,
            "imageUrl": "/mock/spoton.png",
            "rating": 4.7,
            "stock": 55,
            "description": "Monthly topical treatment. Kills fleas, ticks, and lice. Water-resistant.",
            "prescriptionRequired": False,
        },
        {
            "name": "Digestive Probiotic Powder",
            "category": "Supplement",
            "petType": "Dog",
            "price": 479.00,
            "imageUrl": "/mock/probiotic.png",
            "rating": 4.5,
            "stock": 70,
            "description": "Supports gut health and digestion. Mix with food. Vet-approved strains.",
            "prescriptionRequired": False,
        },
        {
            "name": "Eye Drops for Irritation (Dogs & Cats)",
            "category": "Medicine",
            "petType": "Dog",
            "price": 279.00,
            "imageUrl": "/mock/eye.png",
            "rating": 4.4,
            "stock": 40,
            "description": "Lubricating eye drops for minor irritation. See vet for persistent issues.",
            "prescriptionRequired": False,
        },
        {
            "name": "Dental Water Additive for Dogs",
            "category": "Medicine",
            "petType": "Dog",
            "price": 329.00,
            "imageUrl": "/mock/dental.png",
            "rating": 4.6,
            "stock": 65,
            "description": "Add to drinking water to reduce plaque and freshen breath. No brushing needed.",
            "prescriptionRequired": False,
        },
        {
            "name": "Hairball Relief Gel for Cats",
            "category": "Medicine",
            "petType": "Cat",
            "price": 299.00,
            "imageUrl": "/mock/hairball.png",
            "rating": 4.5,
            "stock": 80,
            "description": "Petroleum-free hairball remedy. Helps pass hairballs naturally.",
            "prescriptionRequired": False,
        },
        {
            "name": "Avian Calcium Tonic",
            "category": "Supplement",
            "petType": "Bird",
            "price": 259.00,
            "imageUrl": "/mock/vitamin.png",
            "rating": 4.4,
            "stock": 45,
            "description": "Supports beak, bone, and egg-laying health in companion birds.",
            "prescriptionRequired": False,
        },
        {
            "name": "Bird Mite Relief Drops",
            "category": "Medicine",
            "petType": "Bird",
            "price": 349.00,
            "imageUrl": "/mock/medicine2.png",
            "rating": 4.2,
            "stock": 30,
            "description": "Topical mite control for caged birds. Use only as directed by a vet.",
            "prescriptionRequired": True,
        },
        {
            "name": "Rabbit Gut Support Syrup",
            "category": "Medicine",
            "petType": "Small Pet",
            "price": 319.00,
            "imageUrl": "/mock/probiotic.png",
            "rating": 4.6,
            "stock": 34,
            "description": "Digestive support for rabbits and guinea pigs during appetite loss or stress.",
            "prescriptionRequired": False,
        },
        {
            "name": "Small Pet Vitamin C Drops",
            "category": "Supplement",
            "petType": "Small Pet",
            "price": 229.00,
            "imageUrl": "/mock/vitamin.png",
            "rating": 4.5,
            "stock": 52,
            "description": "Daily vitamin C support for guinea pigs and other small pets needing supplementation.",
            "prescriptionRequired": False,
        },
        {
            "name": "Aquarium Anti-Fungal Treatment",
            "category": "Medicine",
            "petType": "Fish",
            "price": 289.00,
            "imageUrl": "/mock/medicine.png",
            "rating": 4.3,
            "stock": 48,
            "description": "Water treatment for common fungal infections in aquarium fish.",
            "prescriptionRequired": False,
        },
        {
            "name": "Aquarium Water Conditioner",
            "category": "Supplement",
            "petType": "Fish",
            "price": 199.00,
            "imageUrl": "/mock/filter.png",
            "rating": 4.7,
            "stock": 95,
            "description": "Neutralizes chlorine and supports a healthier aquarium environment.",
            "prescriptionRequired": False,
        },
        {
            "name": "General Pet Recovery Tonic",
            "category": "Supplement",
            "petType": "Other",
            "price": 399.00,
            "imageUrl": "/mock/vitamin.png",
            "rating": 4.1,
            "stock": 25,
            "description": "General nutritional support tonic for exotic and miscellaneous companion pets.",
            "prescriptionRequired": False,
        },
    ]

    existing_medicine_names = {
        item.get("name")
        for item in mongo.db.medicines.find({}, {"name": 1})
        if item.get("name")
    }
    missing_medicines = [medicine for medicine in medicines if medicine["name"] not in existing_medicine_names]
    if missing_medicines:
        mongo.db.medicines.insert_many(missing_medicines)

